<?php

/**
 * @file
 * Custom Header Image .module file
 *
 * This is a small condensed .module file to increase performance. Heavy
 * Processing is done in the customheaderimage.admin.inc file
 */

/**
* Implements hook_init().
*/
function customheaderimage_init() {
  define('CSS_PATH', drupal_get_path('module', 'customheaderimage') . '/css/customheaderimage_style.css');
  define('ADMIN_CSS_PATH', drupal_get_path('module', 'customheaderimage') . '/css/customheaderimage_admin_style.css');
  define('FILES_PATH', variable_get('file_public_path', conf_path() . '/files'));
  //define('drupal_get_path('module', 'customheaderimage')', drupal_get_path('module', 'customheaderimage'));
  define('MODULE_CONFIG_BASE_PATH', 'admin/config/media/customheaderimage');

  drupal_add_css(CSS_PATH, array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  drupal_add_css(ADMIN_CSS_PATH, array('group' => CSS_DEFAULT, 'every_page' => TRUE));

}

/**
 * Implements hook_menu().
 */
function customheaderimage_menu() {
  // Module settings.
  $items['admin/config/media/customheaderimage'] = array(
    'title' => 'Custom Header Image',
    'description' => 'Configuration for path specific header images. Suppports pages and views.',
    'page callback' => 'customheaderimage_display_pathspecific',
    'access arguments' => array('administer customheaderimage'),
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  $items['admin/config/media/customheaderimage/default'] = array(
    'title' => 'Path Specific',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/media/customheaderimage/global'] = array(
    'title' => 'Global',
    'description' => 'Configuration for global default headers',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('customheaderimage_edit_image_form'),
    'access callback' => TRUE,
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  $items['admin/config/media/customheaderimage/edit'] = array(
    'title' => 'Edit',
    'description' => 'Edit the header image associated with this path',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('customheaderimage_edit_image_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  $items['admin/config/media/customheaderimage/delete'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Delete Header Image',
    'description' => 'Delete specific path image',
    'page callback' => 'customheaderimage_delete',
    'access arguments' => array('administer customheaderimage'),
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function customheaderimage_permission() {
  return array(
    'administer customheaderimage' => array(
      'title' => t('Administer Custom Header Images'),
      'description' => t('Perform administration tasks for Custom Header Image module.'),
    ),
  );
}
