<?php

/**
* Implements hook_init().
*/
function customheaderimage_init() {
  $css_path = drupal_get_path('module', 'customheaderimage') .'/css/customheaderimage_style.css';
	drupal_add_css($css_path, array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  //Below is for testing purposes
  //customheaderimage_add_rule('node/2', '/sites/default/files/bookpurchase_1.jpg');

  //customheaderimage_update_image('.page-node-1', $css_path, '/sites/default/files/bookpurchase_1.jpg', '/images.jpg');
}

/**
 * Implements hook_menu().
 */
function customheaderimage_menu() {
  // Module settings.
  $items['admin/config/customheaderimage'] = array(
    'title' => 'Custom Header Image',
    'description' => 'Configuration for path specific header imagesn',
    'page callback' => 'customheaderimage_display_pathspecific',
    'access arguments' => array('administer customheaderimage'),
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  $items['admin/config/customheaderimage/default'] = array(
    'title' => 'Path Specific',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/customheaderimage/global'] = array(
    'title' => 'Global',
    'description' => 'Configuration for global default headers',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'customheaderimage_display_global',
    'access arguments' => array('administer customheaderimage'),
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  $items['admin/config/customheaderimage/edit'] = array(
    'title' => 'Edit',
    'description' => 'Edit the header image associated with this path',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('customheaderimage_edit_image_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'customheaderimage.admin.inc',
    'file path' => drupal_get_path('module', 'customheaderimage'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function customheaderimage_permission() {
  return array(
    'administer customheaderimage' => array(
      'title' => t('Administer Custom Header Images'),
      'description' => t('Perform administration tasks for Custom Header Image module.'),
    ),
  );
}

function customheaderimage_slashtodash($string) {
  return str_replace('/', '--', $string);
}
function customheaderimage_dashtoslash($string) {
  return str_replace('--', '/', $string);
}
